//register all the possible indicator actions

export const DATAELEMENTS_REQUESTED = 'indicators.DATAELEMENTS_REQUESTED'
export const DATAELEMENTS_RECEIVED = 'indicators.DATAELEMENTS_RECEIVED'

export const INDICATORGROUP_REQUESTED = 'indicators.INDICATORGROUP_REQUESTED'
export const INDICATORGROUP_RECEIVED = 'indicators.INDICATORGROUP_RECEIVED'

export const INDICATORGROUP_INDICATORS_REQUESTED = 'indicators.INDICATORGROUP_INDICATORS_REQUESTED'
export const INDICATORGROUP_INDICATORS_RECEIVED = 'indicators.INDICATORGROUP_INDICATORS_RECEIVED'

export const FACILITY_DATAELEMENT_DATAVALUES_REQUESTED = 'indicators.FACILITY_DATAELEMENT_DATAVALUES_REQUESTED'
export const FACILITY_DATAELEMENT_DATAVALUES_RECEIVED = 'indicators.FACILITY_DATAELEMENT_DATAVALUES_RECEIVED'