export const JOB_TYPES_REQUESTED = 'staff.JOB_TYPES_REQUESTED'
export const JOB_TYPES_RECEIVED = 'staff.JOB_TYPES_RECEIVED'

export const CADRES_REQUESTED = 'staff.CADRES_REQUESTED'
export const CADRES_RECEIVED = 'staff.CADRES_RECEIVED'

export const FACILITY_STAFF_REQUESTED = 'staff.FACILITY_STAFF_REQUESTED'
export const FACILITY_STAFF_RECEIVED = 'staff.FACILITY_STAFF_RECEIVED'

export const CLEAR_FACILITY_STAFF_DATA_REQUESTED = 'staff.CLEAR_FACILITY_STAFF_REQUESTED'
export const ADD_SELECTED_FACILITY_JOB_TYPE_REQUESTED = 'staff.ADD_SELECTED_FACILITY_JOB_TYPE_REQUESTED'
export const ADD_SELECTED_FACILITY_JOB_TYPE_SUCCESS = 'staff.ADD_SELECTED_FACILITY_JOB_TYPE_SUCCESS'

export const REMOVE_SELECTED_FACILITY_JOB_TYPE_REQUESTED = 'staff.REMOVE_SELECTED_FACILITY_JOB_TYPE_REQUESTED'
export const REMOVE_SELECTED_FACILITY_JOB_TYPE_SUCCESS = 'staff.REMOVE_SELECTED_FACILITY_JOB_TYPE_SUCCESS'

export const GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_REQUESTED = 'staff.GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_REQUESTED'
export const GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_VALUES_RECEIVED = 'staff.GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_VALUES_RECEIVED'
export const GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_VALUES_ERROR = 'staff.GET_FACILITY_INDIVIDUAL_SELECTED_JOB_TYPES_VALUES_ERROR'
