export const PRODUCTS_REQUESTED = 'commodities.PRODUCTS_REQUESTED'
export const PRODUCTS_RECEIVED = 'commodities.PRODUCTS_RECEIVED'

export const FACILITY_PRODUCTS_REQUESTED = 'commodities.FACILITY_PRODUCTS_REQUESTED'
export const FACILITY_PRODUCTS_RECEIVED = 'commodities.FACILITY_PRODUCTS_RECEIVED'