//register all the possible facility actions

export const FACILITY_TYPES_REQUESTED = 'facility.FACILITY_TYPES_REQUESTED'
export const FACILITY_TYPES_RECEIVED = 'facility.FACILITY_TYPES_RECEIVED'

export const FACILITY_KEPH_LEVELS_REQUESTED = 'facility.FACILITY_KEPH_LEVELS_REQUESTED'
export const FACILITY_KEPH_LEVELS_RECEIVED = 'facility.FACILITY_KEPH_LEVELS_RECEIVED'
