//register all the possible facility actions


export const COUNTY_CODES_FETCHED = 'facility.COUNTY_CODES_FETCHED'

export const COUNTY_CONSTITUENCY_CODES_REQUESTED = 'facility.COUNTY_CONSTITUENCY_CODES_REQUESTED'
export const COUNTY_CONSTITUENCY_CODES_FETCHED = 'facility.COUNTY_CONSTITUENCY_CODES_FETCHED'

export const CONSTITUENCY_WARD_CODES_REQUESTED = 'facility.CONSTITUENCY_WARD_CODES_REQUESTED'
export const CONSTITUENCY_WARD_CODES_FETCHED = 'facility.CONSTITUENCY_WARD_CODES_FETCHED'

export const FACILITY_TYPES_REQUESTED = 'facility.FACILITY_TYPES_REQUESTED'
export const FACILITY_TYPES_RECEIVED = 'facility.FACILITY_TYPES_RECEIVED'
