//register all the possible facility actions
export const FACILITY_LIST_REQUESTED = 'facility.FACILITY_LIST_REQUESTED'
export const FACILITY_LIST_RECEIVED = 'facility.FACILITY_LIST_RECEIVED'

export const FACILITY_DETAILS_REQUESTED = 'facility.FACILITY_DETAILS_REQUESTED'
export const FACILITY_DETAILS_RECEIVED = 'facility.FACILITY_DETAILS_RECEIVED'

export const COUNTY_SUMMARY_REQUESTED = 'facility.COUNTY_SUMMARY_REQUESTED'
export const COUNTY_SUMMARY_RECEIVED = 'facility.COUNTY_SUMMARY_RECEIVED'

export const CONSTITUENCY_SUMMARY_REQUESTED = 'facility.CONSTITUENCY_SUMMARY_REQUESTED'
export const CONSTITUENCY_SUMMARY_RECEIVED = 'facility.CONSTITUENCY_SUMMARY_RECEIVED'

export const WARD_SUMMARY_REQUESTED = 'facility.WARD_SUMMARY_REQUESTED'
export const WARD_SUMMARY_RECEIVED = 'facility.WARD_SUMMARY_RECEIVED'

export const FACILITY_TYPES_REQUESTED = 'facility.FACILITY_TYPES_REQUESTED'
export const FACILITY_TYPES_RECEIVED = 'facility.FACILITY_TYPES_RECEIVED'

export const FACILITY_KEPH_LEVELS_REQUESTED = 'facility.FACILITY_KEPH_LEVELS_REQUESTED'
export const FACILITY_KEPH_LEVELS_RECEIVED = 'facility.FACILITY_KEPH_LEVELS_RECEIVED'

export const CHANGE_FACILITY_INFORMATION_TYPE = 'facility.CHANGE_FACILITY_INFORMATION_TYPE'

export const CHANGE_FACILITY_FILTER = 'facility.CHANGE_FACILITY_FILTER'