//register all the possible common actions
export const COUNTY_CODES_FETCHED = 'common.COUNTY_CODES_FETCHED'

export const COUNTY_CONSTITUENCY_CODES_REQUESTED = 'common.COUNTY_CONSTITUENCY_CODES_REQUESTED'
export const COUNTY_CONSTITUENCY_CODES_FETCHED = 'common.COUNTY_CONSTITUENCY_CODES_FETCHED'

export const CONSTITUENCY_WARD_CODES_REQUESTED = 'common.CONSTITUENCY_WARD_CODES_REQUESTED'
export const CONSTITUENCY_WARD_CODES_FETCHED = 'common.CONSTITUENCY_WARD_CODES_FETCHED'

export const CHANGE_LEVEL = 'common.CHANGE_LEVEL'
export const CHANGE_CURRENT_ID = 'common.CHANGE_CURRENT_ID'